# Generated by Django 3.2.16 on 2022-10-20 01:07

from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('original_value', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.supplier')),
            ],
        ),
    ]
