# Generated by Django 3.2.16 on 2022-10-20 01:58

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221020_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='original_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, null=True),
        ),
    ]
