# Generated by Django 3.2.16 on 2022-10-20 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_payments_original_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests', models.CharField(blank=True, choices=[('solicitação', 'solicitação'), ('liberação', 'liberação'), ('negação', 'negação')], max_length=30, null=True)),
                ('payments', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.supplier')),
            ],
        ),
    ]
