# Generated by Django 3.2.16 on 2022-10-20 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='payments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.payments'),
        ),
    ]
