# Generated by Django 3.2.16 on 2022-10-20 10:04

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_company_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='corporate_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Razão Social'),
        ),
    ]
