# Generated by Django 3.2.16 on 2022-10-20 10:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221020_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='payments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.payments', verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='company',
            name='requests',
            field=models.CharField(blank=True, choices=[('solicitação', 'solicitação'), ('liberação', 'liberação'), ('negação', 'negação')], max_length=30, null=True, verbose_name='Antecipação de Pagamento'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='Supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='original_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, null=True, verbose_name='Valor Original'),
        ),
    ]
