# Generated by Django 3.2.16 on 2022-10-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221020_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='requests',
            field=models.CharField(blank=True, choices=[('S', 'Solicitado'), ('A', 'Aprovado'), ('N', 'Negado')], max_length=30, null=True, verbose_name='Antecipação de Pagamento'),
        ),
    ]
