# Generated by Django 3.2.16 on 2022-10-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_payments_request_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company',
            new_name='Request',
        ),
    ]
