# Generated by Django 3.2.16 on 2022-10-20 13:27

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_company_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Razão Social')),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
            ],
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='Supplier',
            new_name='supplier',
        ),
    ]
