# Generated by Django 3.2.16 on 2022-10-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20221021_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='request_status',
            field=models.CharField(blank=True, choices=[('Indisponível', 'Indisponível'), ('Disponível', 'Disponível'), ('Aguardando confirmação', 'Aguardando confirmação'), ('Antecipado', 'Antecipado'), ('Negado', 'Negado')], default='Disponível', max_length=30, null=True, verbose_name='Status da Solicitação'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requests',
            field=models.CharField(blank=True, choices=[('Solicitado', 'Solicitado'), ('Aprovado', 'Aprovado'), ('Negado', 'Negado')], max_length=30, null=True, verbose_name='Antecipação de Pagamento'),
        ),
    ]
