# Generated by Django 3.2.16 on 2022-10-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20221021_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_of_issue',
            field=models.DateField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
    ]
