# Generated by Django 3.2.16 on 2022-10-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_payments_date_of_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='date_of_issue',
        ),
    ]
