# Generated by Django 3.2.16 on 2022-10-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_payments_date_of_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='date_of_issue',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
