# Generated by Django 3.2.16 on 2022-10-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_payments_date_of_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_of_issue',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
