# Generated by Django 3.2.16 on 2022-10-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_payments_date_of_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_of_issue',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
