# Generated by Django 3.2.16 on 2022-10-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_request_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name_plural': 'Space X'},
        ),
    ]
